import{S as y,a as m,i as h}from"./assets/vendor-da186403.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const d of t.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const L="42222554-b2624bd1f455ca6190f2bf509",p=document.querySelector(".gallery");function v(r){const a=r.map(s=>`<li class="gallery-item">
             <div class="card-top">
            <a class="card-link" href="${s.largeImageURL}">
                <img class="card-image" src="${s.webformatURL}" alt="${s.tags}">
            </a>
        </div>
        <div class="card-bottom">
            <p class="card-likes">Likes <span class="card-value">${s.likes}</span></p>
            <p class="card-views">Views <span class="card-value">${s.views}</span></p>
            <p class="card-comments">Comments <span class="card-value">${s.comments}</span></p>
            <p class="card-downloads">Downloads <span class="card-value">${s.downloads}</span></p>
        </div>
        </li>`).join("");return p.insertAdjacentHTML("beforeend",a),a}const f=document.querySelector(".search-form"),b=document.querySelector(".search-field"),i=document.querySelector(".more-photos"),o=document.querySelector(".loader");let l="",w=new y(".gallery a",{}),c=1,u=15;m.defaults.baseURL="https://pixabay.com/api/";f.addEventListener("submit",S);function S(r){if(r.preventDefault(),p.innerHTML="",l=b.value.trim(),l===""){$();return}g(l,c),i.classList.add("hidden"),f.reset()}i.addEventListener("click",P);async function P(){c+=1,await g(l,c);const r=Math.ceil(100/u);if(c>r)return i.classList.add("hidden"),h.error({position:"topRight",message:"We are sorry, but you have reached the end of search results"})}async function g(r,a){const s=new URLSearchParams({per_page:u,page:c});try{o.classList.remove("hidden");const e=(await m.get(`?key=${L}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&${s}`)).data;v(e.hits),w.refresh(),o.classList.add("hidden"),(a-1)*u+e.hits.length<e.totalHits?(o.classList.remove("hidden"),i.classList.remove("hidden"),o.classList.add("hidden")):i.classList.add("hidden"),e.hits.length===0&&(o.classList.add("hidden"),h.error({position:"topRight",message:"Sorry, there are no images matching <br/> your search query. Please try again!"}))}catch(n){console.error("Error fetching images:",n),o.classList.add("hidden")}}function $(){p.innerHTML="",i.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
